server:
  port: 8084

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://${NOTIFICATION_DATABASE_HOST}:${NOTIFICATION_DATABASE_PORT}/${NOTIFICATION_DATABASE_NAME}
    username: ${NOTIFICATION_DATABASE_USERNAME}
    password: ${NOTIFICATION_DATABASE_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    topic:
      notification: notification
      notification-dlq: notification-dlq
    consumer:
      auto-offset-reset: latest
      group-id: notification_group
