server:
  port: 8080

spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://${ORDER_DATABASE_HOST}:${ORDER_DATABASE_PORT}/${ORDER_DATABASE_NAME}
    username: ${ORDER_DATABASE_USERNAME}
    password: ${ORDER_DATABASE_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  sql:
    init:
      mode: never # change to always on first run
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    topic:
      order-ending-success: order-ending-success
      order-ending-fail: order-ending-fail
      orchestrator: orchestrator
    consumer:
      auto-offset-reset: latest
      group-id: order_group
