server:
  port: 8083

spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://${PAYMENT_DATABASE_HOST}:${PAYMENT_DATABASE_PORT}/${PAYMENT_DATABASE_NAME}
    username: ${PAYMENT_DATABASE_USERNAME}
    password: ${PAYMENT_DATABASE_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    topic:
      payment-validation: payment-validation
      payment-validation-failed: payment-validation-failed
      orchestrator: orchestrator
    consumer:
      auto-offset-reset: latest
      group-id: payment_group
